# **Dados e Aprendizagem Automática**

## **Data Exploration - Test Dataset**

In [1]:
import sklearn as skl
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
%matplotlib inline

*Load the CSVs*

In [2]:
df_test = pd.read_csv('../Datasets/test_data.csv', encoding='latin-1')

### **Exploratory Data Analysis (EDA)**

In [3]:
df_test.head()

,city_name,record_date,AVERAGE_FREE_FLOW_SPEED,AVERAGE_TIME_DIFF,AVERAGE_FREE_FLOW_TIME,LUMINOSITY,AVERAGE_TEMPERATURE,AVERAGE_ATMOSP_PRESSURE,AVERAGE_HUMIDITY,AVERAGE_WIND_SPEED,AVERAGE_CLOUDINESS,AVERAGE_PRECIPITATION,AVERAGE_RAIN
0,Porto,2019-02-13 23:00:00,39.2,0.0,91.0,DARK,8.0,1026.0,71.0,1.0,cï¿½u claro,0.0,NaN
1,Porto,2018-11-28 20:00:00,42.5,12.2,76.8,DARK,11.0,1020.0,93.0,4.0,nuvens dispersas,0.0,NaN
2,Porto,2018-08-14 05:00:00,45.9,0.0,86.3,DARK,14.0,1017.0,93.0,0.0,NaN,0.0,NaN
3,Porto,2019-07-06 17:00:00,33.2,51.7,89.9,LIGHT,22.0,1016.0,77.0,4.0,cï¿½u pouco nublado,0.0,NaN
4,Porto,2018-10-15 06:00:00,44.0,3.5,85.5,DARK,12.0,1004.0,100.0,9.0,NaN,0.0,chuva fraca

In [4]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   city_name                1500 non-null   object
 1   record_date              1500 non-null   object
 2   AVERAGE_FREE_FLOW_SPEED  1500 non-null   float64
 3   AVERAGE_TIME_DIFF        1500 non-null   float64
 4   AVERAGE_FREE_FLOW_TIME   1500 non-null   float64
 5   LUMINOSITY               1500 non-null   object
 6   AVERAGE_TEMPERATURE      1500 non-null   float64
 7   AVERAGE_ATMOSP_PRESSURE  1500 non-null   float64
 8   AVERAGE_HUMIDITY         1500 non-null   float64
 9   AVERAGE_WIND_SPEED       1500 non-null   float64
 10  AVERAGE_CLOUDINESS       901 non-null    object
 11  AVERAGE_PRECIPITATION    1500 non-null   float64
 12  AVERAGE_RAIN             140 non-null    object
dtypes: float64(8), object(5)
memory usage: 152.5+ KB

In [5]:
df_test.describe()

,AVERAGE_FREE_FLOW_SPEED,AVERAGE_TIME_DIFF,AVERAGE_FREE_FLOW_TIME,AVERAGE_TEMPERATURE,AVERAGE_ATMOSP_PRESSURE,AVERAGE_HUMIDITY,AVERAGE_WIND_SPEED,AVERAGE_PRECIPITATION
count,1500.0000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.0
mean,40.8304,26.750533,81.194333,16.104000,1017.457333,80.734000,3.116667,0.0
std,4.2396,34.089866,8.189691,5.094293,5.840455,17.729358,2.198699,0.0
min,31.0000,0.000000,48.100000,1.000000,985.000000,14.000000,0.000000,0.0
25%,37.5000,2.500000,75.800000,13.000000,1015.000000,72.000000,1.000000,0.0
50%,41.0000,12.600000,82.300000,16.000000,1018.000000,86.000000,3.000000,0.0
75%,43.9000,40.225000,87.600000,19.000000,1021.000000,93.000000,4.000000,0.0
max,56.2000,232.300000,106.100000,32.000000,1033.000000,100.000000,13.000000,0.0

Missing values

In [6]:
df_test.isna().any()

city_name                  False
record_date                False
AVERAGE_FREE_FLOW_SPEED    False
AVERAGE_TIME_DIFF          False
AVERAGE_FREE_FLOW_TIME     False
LUMINOSITY                 False
AVERAGE_TEMPERATURE        False
AVERAGE_ATMOSP_PRESSURE    False
AVERAGE_HUMIDITY           False
AVERAGE_WIND_SPEED         False
AVERAGE_CLOUDINESS          True
AVERAGE_PRECIPITATION      False
AVERAGE_RAIN                True
dtype: bool

In [7]:
print(df_test.isna().sum())

city_name                     0
record_date                   0
AVERAGE_FREE_FLOW_SPEED       0
AVERAGE_TIME_DIFF             0
AVERAGE_FREE_FLOW_TIME        0
LUMINOSITY                    0
AVERAGE_TEMPERATURE           0
AVERAGE_ATMOSP_PRESSURE       0
AVERAGE_HUMIDITY              0
AVERAGE_WIND_SPEED            0
AVERAGE_CLOUDINESS          599
AVERAGE_PRECIPITATION         0
AVERAGE_RAIN               1360
dtype: int64

Outros

In [8]:
df_test['AVERAGE_RAIN']

0                  NaN
1                  NaN
2                  NaN
3                  NaN
4          chuva fraca
             ...
1495       chuva fraca
1496               NaN
1497               NaN
1498    chuva moderada
1499               NaN
Name: AVERAGE_RAIN, Length: 1500, dtype: object

In [9]:
df_test['AVERAGE_RAIN'].value_counts()

AVERAGE_RAIN
chuva fraca                68
chuva moderada             35
aguaceiros fracos          12
chuva leve                 11
chuva                       9
aguaceiros                  2
trovoada com chuva          1
chuvisco fraco              1
trovoada com chuva leve     1
Name: count, dtype: int64

In [10]:
df_test['AVERAGE_PRECIPITATION'].unique()

array([0.])

In [11]:
df_test['AVERAGE_CLOUDINESS'].value_counts()

AVERAGE_CLOUDINESS
cï¿½u claro            345
cï¿½u pouco nublado    109
algumas nuvens          98
nuvens quebrados        96
nuvens quebradas        95
nuvens dispersas        94
cï¿½u limpo             27
tempo nublado           20
nublado                 17
Name: count, dtype: int64

In [12]:
df_test['LUMINOSITY'].value_counts()

LUMINOSITY
DARK         730
LIGHT        725
LOW_LIGHT     45
Name: count, dtype: int64